### ISSUE TITLE
ReflectionException' with message 'Method Closure::__call() does not exist

### ISSUE THREAD

**Issue by marden** [getsentry/raven-php#106]
The Raven_Stacktrace class doesn't handle frame context when frame is a Closure. In this case *get_frame_context* method throws the uncaught exception on the line:

    $reflection = new ReflectionMethod($frame['class'], '__call');

Enviroment:
- PHP 5.4.13
- ZF2-based project

**Comment by tucksaun** [comment]
Can probably be closed as it seams to be fixed in 825d5d3098ece7e20c284de114635391ed2e4c3a
