### ISSUE TITLE
Trigger Built-In Exception Handler

### ISSUE THREAD

**Issue by chriscannon** [getsentry/raven-php#169]
Is there a way to trigger PHP's built-in exception handler even when I invoke registerExceptionHandler()? I see that the function does save the old exception handler function, but when no custom exception handler is defined which means that PHP's built-in function is set the value of the old exception handler is NULL. Ideally what I would like to happen is that when an exception occurs Sentry logs the exception as well as doing whatever the built-in PHP exception handler would do (e.g., write to the PHP error log, output to stderr, etc.).

**Comment by josephmc5** [comment]
This one is getting me too. I think I'll have to do like @iinfo-dev-mk is saying and just log to file with a custom exception handler.
