### ISSUE TITLE
Messages not showing when using Sentry 7.1.4

### ISSUE THREAD

**Issue by aubm** [getsentry/raven-php#188]
Hello there, I have been working on a fresh install of the latest version of Sentry (currently 7.1.4). After everything seemed to work on my virtual machine I tried to send messages from a php sample app but unfortunatly they won't appear.

Here is a line coming from the nginx access_log file telling us the API is actually called.

![capture d ecran 2015-01-24 a 00 07 17](https://cloud.githubusercontent.com/assets/6061115/5884407/4142e53c-a35d-11e4-8ce7-891d8e89f64f.png)

As I said, the sentry web page shows nothing. I checked using PGAdmin to ensure that the sentry_message table was empty.

![capture d ecran 2015-01-24 a 00 10 18](https://cloud.githubusercontent.com/assets/6061115/5884441/b8e8186e-a35d-11e4-99eb-b3ce45dca9da.png)

I did not look deeper yet but I think it has something to do with the sentry version. I use raven-php to report errors from php apps on a sentry 6 server and it works fine.

Does anyone has encountered this problem?

**Comment by dcramer** [comment]
It looks like the sample app is sending to the wrong endpoint

It should be ``/api/{project_id}/store/``

**Comment by dcramer** [comment]
Uh oh, this almost looks like its an internal issue. Let me dig some more.

**Comment by dcramer** [comment]
Ignore the PHP concern I have above, but it's likely you're misconfigured.

Take a look at the upgrade page + CHANGES for 7.0. There's a lot of changes and we recommend regenerating your config.

**Comment by dcramer** [comment]
Sorry I also realize i misread and you said fresh install. It sounds like workers probably aren't running.

If you've confirmed workers + celerybeat (i.e. -B) are running and nothings recording please reopen, but this is a server-related configuration issue most likely.

**Comment by aubm** [comment]
Hum, looks like it's a configuration issue indeed. Sorry, my fault and thank you for your time.
