### ISSUE TITLE
First-class Laravel support

### ISSUE THREAD

**Issue by dcramer** [getsentry/raven-php#196]
This doesn't have to be part of raven-php, but it should be something we (the Sentry Team) own.

See also:

- https://github.com/rcrowe/Raven
- https://github.com/jenssegers/laravel-raven
- http://www.neontsunami.com/posts/using-sentry-for-log-tracking-with-laravel

Also a big chunk of this simply could be documentation.

**Comment by smazurov** [comment]
[laravel-raven](https://github.com/jenssegers/laravel-raven) is a good implementation, linking to it would get people set up well.

**Comment by ameliaikeda** [comment]
In Laravel 4, the recommended way to set up logging is adding a handler to monolog. In laravel 5, it's `App\Exceptions\Handler::report(Exception $e)`. We could easily make a service provider to automatically do this (after #197, etc are finished).

**Comment by jbrooksuk** [comment]
I'm working on a nicer logger implementation. https://github.com/AltThree/Sentry

**Comment by dcramer** [comment]
I've added some docs for this, as Monolog supports Sentry by default these days (afaict).
