### ISSUE TITLE
Could not parse version constraint ^1.8.0: Invalid version string "^1.8.0"

### ISSUE THREAD

**Issue by jhnferraris** [getsentry/raven-php#218]
In composer.json the package version of fabpot/php-cs-fixer is `^1.8.0`. When running composer install it throws an invalid version string.  Checking [packagist.org](https://packagist.org/packages/fabpot/php-cs-fixer), the version there is `1.8`. Maybe the composer.json should point to that version without `0`?

**Comment by dcramer** [comment]
What version of composer? Try updating and see if that resolves it

**Comment by jhnferraris** [comment]
Fixed by updating composer. My bad
