### ISSUE TITLE
Application environment

### ISSUE THREAD

**Issue by wayneashleyberry** [getsentry/raven-php#222]
What's the correct way to add application environment context?

I'm currently doing this:

```php
    $client = new Raven_Client(Config::get('services.raven.dsn'));

    $context = [
        'extra' => [
            'environment' => App::environment(),
            'host'        => Request::server('HTTP_HOST'),
            'server'      => Request::server('SERVER_NAME'),
        ]
    ];

    $client->captureException($e, $context);
```

**Comment by wayneashleyberry** [comment]
But when I view exceptions being reported, there is no associated environment:

```
ENVIRONMENT
No data available.
```

**Comment by dcramer** [comment]
@wayneashleyberry The environment listed under request is related to the HTTP context (it's the env key):

https://docs.getsentry.com/hosted/clientdev/interfaces/#context-interfaces
