### ISSUE TITLE
Discarded invalid parameter 'curl_method'

### ISSUE THREAD

**Issue by wayneashleyberry** [getsentry/raven-php#224]
Setting the `curl_method` as per https://github.com/getsentry/raven-php#curl_method seems to be causing an error.

![screen shot 2015-08-12 at 11 35 01 am](https://cloud.githubusercontent.com/assets/727262/9220898/36f561e6-40e6-11e5-80b9-a4422dad3bb6.png)

Using the latest version of `raven/raven` as of 2015-08-12T11:36:40+0200

```sh
$ composer show -i
raven/raven 0.12.0 A PHP client for Sentry (http://getsentry.com)
```

Here's my test code:

```php
<?php

define('RAVEN_DSN', '***');

require_once('vendor/autoload.php');

$client = new Raven_Client(RAVEN_DSN);

$client->user_context([
    'id' => mt_rand()
]);

$e = new Exception('testing...');

$client->captureException($e, [
    'curl_method' => 'async',
    'tags' => [
        'environment' => 'testing'
    ]
]);
```

**Comment by dcramer** [comment]
Ah, your captureException call is incorrect.

You need to specify the curl_method as part of runtime options

```
new Raven_Client(DSN, array('curl_method' => 'async'));
```

**Comment by wayneashleyberry** [comment]
aaah, thanks @dcramer
