### ISSUE TITLE
Can not set user context

### ISSUE THREAD

**Issue by Jeloo** [getsentry/raven-php#225]
Hi. I use raven-php with laravel 5. I have middleware for authentication with Client::user_context method call inside it. But i always get bugs without user context (can't see any user context on filters but ip). I tried to debug Raven_Client methods and i noticed that after user context is set i can see the needed array with var_dump($this->context->user). But inside of Client::get_user_data var_dump($this->context->user) prints 'null'. Do i use user_context method wrong?

**Comment by Jeloo** [comment]
Sorry, that was my mistake. I can use method Raven_Client::user_context and Raven_Context::user property saves properly. But i still can not get user context on my dashboard. For example, i have user context ['email' => 'foo@bar.gmail.com'], but i still can't see any user context excepting 'ip'

**Comment by dcramer** [comment]
@Jeloo that def should work. If you are able to introspect the JSON data sent to the server that'd help.

**Comment by Jeloo** [comment]
@dcramer thanks for your reply.

well, i get the following json sample:

"sentry.interfaces.User": {
    "email": "foo@bar.gmail.com"
  },

printing Raven_Compat::json_encode($data). So actually request is ok, right?

**Comment by Jeloo** [comment]
i was wrong, it is working for "email" context. Actually, i tried to use it with another context (subdomain, because i'm working on subdomain-based auth). Should it work with any custom context type?

**Comment by dcramer** [comment]
@Jeloo are you simply passing 'subdomain' as a parameter in the user interface?

**Comment by Jeloo** [comment]
$raven_client_instance->user_context('subdomain', 'test');

just like i do it for tags

**Comment by dcramer** [comment]
@Jeloo if thats actually the syntax you're using it would be invalid:

```
user_context(array(
  'email' => 'foo@example.com',
  'subdomain' => 'test'
));
```

If you're not passing any email/id/etc I think it throw it away, but otherwise this should work fine.
