### ISSUE TITLE
Raven 0.12 400 Bad Request

### ISSUE THREAD

**Issue by krodyrobi** [getsentry/raven-php#226]
When issue-ing the `bin/raven test <dsn>` Sentry reports with an 400 error code.

Tried Raven 0.11 and it works. There is something that broke in the latest version.

Also as a note the testing mechanism should check for thins like this since receiving the Done! string is confusing if the actual test failed :D.

**Comment by dcramer** [comment]
@krodyrobi what is the actual error message? I'm unable to reproduce this on the current version of Sentry.

**Comment by krodyrobi** [comment]
Probably it is because I'm using sentry 6.4.4 and not the latest version.
