### ISSUE TITLE
Discarded invalid value for parameter 'extra'

### ISSUE THREAD

**Issue by ctadlock** [getsentry/raven-php#229]
I see this error on the web dashboard for every error. I am not passing any data in for `extra`.

<img width="923" alt="screen shot 2015-08-25 at 3 35 19 pm" src="https://cloud.githubusercontent.com/assets/1539397/9481423/ed300b5c-4b3e-11e5-8ebc-05b9e95092c2.png">

I have confirmed that the PHP client is sending an empty array as the value for `extra`.

<img width="442" alt="screen shot 2015-08-25 at 3 35 44 pm" src="https://cloud.githubusercontent.com/assets/1539397/9481438/146091c4-4b3f-11e5-92bb-de0fd96fb94b.png">

**Comment by dcramer** [comment]
@ctadlock fixed in 0.12.1 (just tagged this release)

**Comment by ctadlock** [comment]
Wow, I expect faster bug fixing turn around next time!

**Comment by dcramer** [comment]
:ship:  :)
