### ISSUE TITLE
All submissions generate a complaint about "extra"

### ISSUE THREAD

**Issue by AD7six** [getsentry/raven-php#250]
On every reported issue where extra data is not passed to capture, I see this:

![screenshot from 2015-12-01 11-41-50](https://cloud.githubusercontent.com/assets/33387/11498569/8794d690-9820-11e5-8135-f30a0a7bbaa4.png)

**Comment by dcramer** [comment]
This is the second report of an incorrectly encoded null value. Going to dig into this as it might be an issue on the server.

**Comment by dcramer** [comment]
Quickly reviewing things on the server, I can't see why this would be. Are you using the latest version of the client?

**Comment by AD7six** [comment]
We were using 0.8.0 until yesterday, when I upgrade to 0.13.0.

However this may not be a client problem.

Using 0.13.0 looking at the raw json from one error report (event id 3b15fc2ddbf5488880759f2c80586afe):

![screen shot 2015-12-01 at 21 29 44](https://cloud.githubusercontent.com/assets/33387/11513328/c112f4f4-9872-11e5-8958-37b1aadcd1cd.png)

The same error, no code changes, the next minute:

![screen shot 2015-12-01 at 21 30 54](https://cloud.githubusercontent.com/assets/33387/11513347/d9bc838a-9872-11e5-96eb-c340417d41a2.png)

**Comment by prewk** [comment]
I'm getting this as well on a freshly set up client without any "extra" added at all. Note that my `value` is `[]` and not `null` as in @AD7six example:

````
There was 1 error encountered while processing this event
Discarded invalid value for parameter 'extra' Collapse
{
  "name": "extra",
  "value": []
}
````

**Comment by dcramer** [comment]
You can look at the CHANGES file to see what is different. 0.12.0 switches to protocol 6 for example.

I'm closing this out as theres no way the client can be sending empty extra data, and there is absolutely no way the server would use an array here
