### ISSUE TITLE
Set error reporting for raven

### ISSUE THREAD

**Issue by GitRon** [getsentry/raven-php#266]
Hi guys,

I'm using raven-php in combination with sentry. It works great but I'd like to set the error level on which the items are sent to sentry. At the moment even notices are sent to sentry.

Imagining that the software I'm currently keeping alive is producing an abundance of notices and all of them are sent to sentry on each user click... well, is there a way to set the level?

Thx
Ron

PS: Here's my question on Stack: http://stackoverflow.com/questions/35885832/configure-what-is-sent-to-sentry-with-php

**Comment by NanneHuiges** [comment]
I've added an answer on that question, but also see #181 I guess

**Comment by GitRon** [comment]
Thx to @NanneHuiges issue solved (for now) at Stack.
