### ISSUE TITLE
Set Release Version

### ISSUE THREAD

**Issue by bassrock** [getsentry/raven-php#268]
I am trying to use the release tracking in The SentryContextProcessor with Symfony 2. I am doing this with:

```php
    public function processRecord($record)
    {
        $record['release'] = $this->getGitSHA();

        return $record;
    }
```

However the release record is not getting added. Is this available in php?

**Comment by dcramer** [comment]
@bassrock We don't support it via context processors, but you can instantiate the client with it:

```
new Raven_Client($dsn, array(
  release => getGitSha(),
));
```

**Comment by bassrock** [comment]
Ok With Symfony 2 how would you do it in the config.yml for monolog?

**Comment by dcramer** [comment]
@bassrock I couldn't really say off hand. You'd need to find a way to get the reference to the client from monolog. It's likely that exists, but we're not overly familiar with the API. If you can get that, you can simply do $client->release = '...';
