### ISSUE TITLE
Bad Serialization

### ISSUE THREAD

**Issue by bradynpoulsen** [getsentry/raven-php#269]
In the [Raven_Serializer](https://github.com/getsentry/raven-php/blob/0.13.0/lib/Raven/Serializer.php) class, literals are wrongfully and inconsistently being serialized for JSON.
* On [lines 51-58](https://github.com/getsentry/raven-php/blob/0.13.0/lib/Raven/Serializer.php#L51-L58), true/false/null/float literals are being converted to their string representations when they SHOULD be represented as literals in JSON.
* This is also inconsistent to [lines 65-66](https://github.com/getsentry/raven-php/blob/0.13.0/lib/Raven/Serializer.php#L65-L66) where integers are being passed along as their literal values.

This issue is resulting in the Sentry application having this issue: getsentry/sentry#2882

**Comment by dcramer** [comment]
@bradynpoulsen thanks for digging into this -- in retrospect pretty obvious. Will get this fixed today.
